---
- name: Configuring target server
  hosts: ubuntu1
  become: yes

  vars:
    source_dir : ../../webserver/
    destin_dir : /home/ubuntu/webserver

  tasks:

  - name: Wait 600 seconds for target server to become reachable
    wait_for_connection:

  - name: Copy source files to target server
    copy: src={{ source_dir }} dest={{ destin_dir }} mode=0755
    
  - name: Run web server
    shell: python3 webserver.py </dev/null >/dev/null 2>&1 &
    async: 2592000
    poll: 0
