---
- name: Configuring target server
  hosts: ubuntu1
  become: yes

  vars:
    source_dir : ../../webserver/
    destin_dir : /home/ubuntu/webserver

  tasks:

  - name: Wait 600 seconds for target server to become reachable
    wait_for_connection:

  - name: Copy source files to target server
    copy: src={{ source_dir }} dest={{ destin_dir }} mode=0755
    
  - name: Start Docker daemon
    service:
      name: docker
      state: started
      enabled: yes
   
  - name: Install Python pip
    command: "apt -y install python3-pip"
  
  - name: Install Python Docker module
    command: "pip install docker-py"
   
  - name: Pull Docker image from Dockerhub
    docker_image:
      name: python:3.8
      source: pull
    
  - name: Build Docker image from Dockerfile
    docker_image: >
      name=webserver:v1
      path=/home/ubuntu/webserver/webserver/infrastructure/docker/
      state=present
      
  - name: Run Docker container
    docker_container:
      name: webserver
      image: webserver
      state: started
      ports:
      - "8888:80"
      detach: true
