---
- name: Configuring target server
  hosts: ubuntu1
  become: yes

  vars:
    source_dir : ../../
    destin_dir : /home/ubuntu/webserver

  tasks:

  - name: Wait 600 seconds for target server to become reachable
    wait_for_connection:

  - name: Copy source files to target server
    copy: src={{ source_dir }} dest={{ destin_dir }} mode=0755
    
  - name: Start Docker daemon
    service:
      name: docker
      state: started
      enabled: yes
   
  - name: Install Python pip
    command: "apt -y install python3-pip"
  
  - name: Install Python Docker module
    command: "pip install docker-py"
   
  - name: Pull Docker image from Dockerhub
    docker_image:
      name: python:3.8
      source: pull
      
  - name: Check if container exist
    command: docker ps -a -q
    register: containerid
  
  - name: Copy logs from running container
    shell: docker cp $(docker ps -a -q):/usr/src/app/webserver_logs.txt /home/ubuntu/
    ansible.bultin.fetch:
      src: /home/ubuntu/webserver_logs.txt
      dest: /home/ubuntu/
    when: containerid.stdout != ""
    
  - name: Stop running containers
    shell: docker stop $(docker ps -a -q);
    when: containerid.stdout != ""
  
  - name: Remove stopped containers
    shell: docker rm $(docker ps -a -q);
    when: containerid.stdout != ""
    
  - name: Remove previous image
    docker_image:
      state: absent
      name: webserver
      tag: v1
    
  - name: Build Docker image from Dockerfile
    docker_image:
      name: webserver:v1
      build:
        path: /home/ubuntu/webserver/
      source: build
      
  - name: Run Docker container
    docker_container:
      name: webserver
      image: webserver:v1
      state: started
      ports:
      - "8888:80"
      detach: yes
